SELECT /*+PARALLEL */ 
JURISDICTION,	
MDM_SP_ID,	
MDM_CONFIG_ID,	
MDM_DEVICE_ID,	
MDM_BADGE_ID,	
CCB_SP_ID,	
CCB_ACCT_ID,	
METER_SN,	
METER_TYPE,	
MSRMT_LOCAL_DTTM,	
MEASUREMENT_DT,	
HOUR_START,	
YM,	
MULTIPLIER,	
READING_VAL,
Previous_Read,
kWh,
MSRMT_VAL,	
MSRMT_UNIT,	
ADDRESS1,	
CITY_STATE_POSTAL

FROM (

SELECT DISTINCT
D1_SP_CHAR.CHAR_VAL AS JURISDICTION,
D1_SP_IDENTIFIER.D1_SP_ID AS MDM_SP_ID, 
D1_INSTALL_EVT.DEVICE_CONFIG_ID AS MDM_CONFIG_ID, 
D1_DVC_CFG.D1_DEVICE_ID AS MDM_DEVICE_ID,
D1_DVC_IDENTIFIER.ID_VALUE AS MDM_BADGE_ID, 
TRIM(D1_SP_IDENTIFIER.ID_VALUE) AS CCB_SP_ID, 
D1_US.US_ID AS CCB_ACCT_ID,
D1_DVC_IDENTIFIER_SN.ID_VALUE AS METER_SN,
D1_DVC.BUS_OBJ_CD AS METER_TYPE,  
D1_MSRMT.MSRMT_LOCAL_DTTM, 
TO_CHAR(D1_MSRMT.MSRMT_LOCAL_DTTM, 'MM-dd-yyyy') AS MEASUREMENT_DT, 
TO_CHAR(D1_MSRMT.MSRMT_LOCAL_DTTM, 'HH AM') HOUR_START, 
TO_CHAR(D1_MSRMT.MSRMT_LOCAL_DTTM, 'yyyy-MM') AS YM,
MAX(D1_MSRMT.COMBINED_MULTIPLIER) AS MULTIPLIER,
SUM(D1_MSRMT.Reading_Val) AS READING_VAL,
LAG(SUM(D1_MSRMT.Reading_Val), 1) OVER (PARTITION BY D1_DVC_IDENTIFIER.ID_VALUE 
|| D1_MEASR_COMP.MEASR_COMP_TYPE_CD ORDER BY D1_MSRMT.MSRMT_LOCAL_DTTM ASC) AS Previous_Read,
SUM(D1_MSRMT.Reading_Val) -
LAG(SUM(D1_MSRMT.Reading_Val), 1) OVER (PARTITION BY D1_DVC_IDENTIFIER.ID_VALUE 
|| D1_MEASR_COMP.MEASR_COMP_TYPE_CD ORDER BY D1_MSRMT.MSRMT_LOCAL_DTTM ASC) AS kWh,
D1_MSRMT.MSRMT_VAL, 
D1_MEASR_COMP.MEASR_COMP_TYPE_CD AS MSRMT_UNIT,
D1_SP.ADDRESS1,
TRIM(D1_SP.CITY) || ' ' || TRIM(D1_SP.STATE) || ' ' || TRIM(D1_SP.POSTAL) AS CITY_STATE_POSTAL

FROM CISADM.D1_SP_IDENTIFIER D1_SP_IDENTIFIER, CISADM.D1_INSTALL_EVT D1_INSTALL_EVT, CISADM.D1_DVC_CFG D1_DVC_CFG,
CISADM.D1_DVC_IDENTIFIER D1_DVC_IDENTIFIER, CISADM.D1_MEASR_COMP D1_MEASR_COMP, CISADM.D1_MSRMT D1_MSRMT, 
CISADM.D1_DVC_IDENTIFIER D1_DVC_IDENTIFIER_SN, CISADM.D1_SP D1_SP, CISADM.D1_US_SP D1_US_SP, CISADM.D1_US D1_US,
CISADM.D1_DVC D1_DVC, CISADM.D1_SP_CHAR D1_SP_CHAR

/* conditions */
WHERE D1_DVC_IDENTIFIER.DVC_ID_TYPE_FLG = 'D1BN' --this is badge number
AND D1_SP_IDENTIFIER.SP_ID_TYPE_FLG = 'D1EI' --this is ccb sp id
AND D1_DVC_IDENTIFIER_SN.DVC_ID_TYPE_FLG = 'D1SN'--this is badge serial number
AND TO_CHAR(D1_MSRMT.MSRMT_LOCAL_DTTM, 'yyyy-MM') >= TO_CHAR(ADD_MONTHS(SYSDATE, - 3), 'yyyy-MM')
AND D1_SP_CHAR.CHAR_TYPE_CD = 'CM-CISDV' 
AND D1_MSRMT.BO_STATUS_CD = 'OK'
AND D1_DVC.BO_STATUS_CD = 'ACTIVE'

AND D1_MEASR_COMP.MEASR_COMP_TYPE_CD IN ('E-KWH-DEL-15', 'E-KVARH-DEL-15', 'E-KWH-DEL', 'E-KVARH-DEL')
--AND D1_MEASR_COMP.MEASR_COMP_TYPE_CD IN ('E-KVARH-DEL')
AND D1_MSRMT.MSRMT_LOCAL_DTTM >= TRUNC(SYSDATE) - 90
--AND(TO_CHAR(D1_MSRMT.MSRMT_LOCAL_DTTM , 'YYYY')) = '2020'

AND D1_DVC_IDENTIFIER.ID_VALUE IN ('1772740435822')

/* joins */
AND D1_INSTALL_EVT.D1_SP_ID = D1_SP_IDENTIFIER.D1_SP_ID
AND D1_INSTALL_EVT.DEVICE_CONFIG_ID = D1_DVC_CFG.DEVICE_CONFIG_ID
AND D1_DVC_CFG.DEVICE_CONFIG_ID = D1_INSTALL_EVT.DEVICE_CONFIG_ID
AND D1_DVC_CFG.D1_DEVICE_ID = D1_DVC_IDENTIFIER.D1_DEVICE_ID
AND D1_DVC_CFG.DEVICE_CONFIG_ID = D1_MEASR_COMP.DEVICE_CONFIG_ID  --JOIN ON METER
AND D1_MEASR_COMP.MEASR_COMP_ID = D1_MSRMT.MEASR_COMP_ID
AND D1_DVC_CFG.D1_DEVICE_ID = D1_DVC_IDENTIFIER_SN.D1_DEVICE_ID
AND D1_SP_IDENTIFIER.D1_SP_ID = D1_SP.D1_SP_ID
AND D1_SP.D1_SP_ID = D1_US_SP.D1_SP_ID
AND D1_US.US_ID = D1_US_SP.US_ID
AND D1_DVC_IDENTIFIER.D1_DEVICE_ID = D1_DVC.D1_DEVICE_ID
AND D1_INSTALL_EVT.D1_SP_ID = D1_SP_CHAR.D1_SP_ID

GROUP BY 
D1_SP_CHAR.CHAR_VAL,
D1_SP_IDENTIFIER.D1_SP_ID, 
D1_INSTALL_EVT.DEVICE_CONFIG_ID, 
D1_DVC_CFG.D1_DEVICE_ID,
D1_DVC_IDENTIFIER.ID_VALUE, 
TRIM(D1_SP_IDENTIFIER.ID_VALUE), 
D1_US.US_ID,
D1_DVC_IDENTIFIER_SN.ID_VALUE,
D1_DVC.BUS_OBJ_CD,  
D1_MSRMT.MSRMT_LOCAL_DTTM, 
TO_CHAR(D1_MSRMT.MSRMT_LOCAL_DTTM, 'MM-dd-yyyy'), 
TO_CHAR(D1_MSRMT.MSRMT_LOCAL_DTTM, 'HH AM'), 
TO_CHAR(D1_MSRMT.MSRMT_LOCAL_DTTM, 'yyyy-MM'),
D1_MSRMT.MSRMT_VAL, 
D1_MEASR_COMP.MEASR_COMP_TYPE_CD,
D1_SP.ADDRESS1,
TRIM(D1_SP.CITY) || ' ' || TRIM(D1_SP.STATE) || ' ' || TRIM(D1_SP.POSTAL)

ORDER BY D1_MSRMT.MSRMT_LOCAL_DTTM DESC
)