SELECT /*+ parallel (4) */ DISTINCT
TRIM(CI_SA.CIS_DIVISION) AS JURISDICTION,
DECODE(TRIM(CI_SA.CIS_DIVISION), 
'GMO', 'Missouri West', 'KCPLM', 'Missouri Metro', 'KCPLK', 'Kansas Metro', 
'WSTRS', 'Kansas Central South', 'WSTRC', 'Kansas Central') AS DIV_ALIAS,

REGEXP_REPLACE(
RTRIM(XMLAGG(XMLELEMENT(E,TRIM(CI_SP.PREM_ID), ',').EXTRACT('//text()') 
ORDER BY CI_SP.PREM_ID).GETCLOBVAL(),','),
'(^|,)([^,]*)(,\2)+','\1\2') AS PREM_IDS,

REGEXP_REPLACE(
RTRIM(XMLAGG(XMLELEMENT(E,TRIM(CI_SP.SP_ID), ',').EXTRACT('//text()') 
ORDER BY CI_SP.SP_ID).GETCLOBVAL(),','),
'(^|,)([^,]*)(,\2)+','\1\2') AS SP_IDS,

REGEXP_REPLACE(
RTRIM(XMLAGG(XMLELEMENT(E,TRIM(ALFD.METER_NBR), ',').EXTRACT('//text()') 
ORDER BY ALFD.METER_NBR).GETCLOBVAL(),','),
'(^|,)([^,]*)(,\2)+','\1\2') AS METER_NBRS,

ALFD.SUBSTATION_ID,
ALFD.FEEDER_ID AS CIRCUT_ID,
ALFD.TRANSFORMER_ID AS FACILITY_ID,

D1_DVC.DEVICE_TYPE_CD,
DECODE(TRIM(CI_SP_CHAR.CHAR_VAL), '1', '120', '2', '120/120', '3', '120/208', '4', '120/240', 
'5', '120/240/208', '6', '240/240', '7', '240/480', '8', '277/480', '9', '480/480') AS SVC_VOLTS,

REGEXP_REPLACE(
RTRIM(XMLAGG(XMLELEMENT(E,TRIM(CI_SA.ACCT_ID), ',').EXTRACT('//text()') 
ORDER BY CI_SA.ACCT_ID).GETCLOBVAL(),','),
'(^|,)([^,]*)(,\2)+','\1\2') AS ACCT_IDS

FROM 
CUSTANALYTICS_DW.AMI_LP_FLAT_DIMENSION ALFD,

CCB1REP.CI_SA CI_SA, 
CCB1REP.CI_ACCT_PER CI_ACCT_PER, 
CCB1REP.CI_PER_NAME CI_PER_NAME, 
CCB1REP.CI_SP CI_SP,

CCB1REP.CI_SP_CHAR CI_SP_CHAR,

MDM1REP.D1_DVC_IDENTIFIER D1_DVC_IDENTIFIER, 
MDM1REP.D1_DVC D1_DVC

/* conditions */
WHERE 
CI_SA.SA_STATUS_FLG <> '70'
AND DVC_ID_TYPE_FLG = 'D1BN'
AND CI_SP_CHAR.CHAR_TYPE_CD (+) = 'CMSVCVLT'

AND CI_ACCT_PER.MAIN_CUST_SW = 'Y'  
AND CI_PER_NAME.PRIM_NAME_SW = 'Y'
AND CI_ACCT_PER.FIN_RESP_SW = 'Y'

--AND CI_SP.PREM_ID = '2895900000'
--AND CI_SP.PREM_ID = '1795461000'
--AND CI_SA.ACCT_ID = '7494823681'   
 
AND CI_SP.PREM_ID = '7014431000'

--AND TRIM(ALFD.SUBSTATION_ID) = '90'

/* joins */
AND ALFD.ACCOUNT_NBR = CI_SA.ACCT_ID
AND ALFD.ACCOUNT_NBR = CI_ACCT_PER.ACCT_ID
AND CI_ACCT_PER.PER_ID = CI_PER_NAME.PER_ID 
AND ALFD.SERVICE_POINT_NBR = CI_SP.SP_ID 
AND ALFD.SERVICE_POINT_NBR = CI_SP_CHAR.SP_ID (+)
AND ALFD.METER_NBR = D1_DVC_IDENTIFIER.ID_VALUE 
AND D1_DVC_IDENTIFIER.D1_DEVICE_ID = D1_DVC.D1_DEVICE_ID

GROUP BY
TRIM(CI_SA.CIS_DIVISION),
DECODE(TRIM(CI_SA.CIS_DIVISION), 
'GMO', 'Missouri West', 'KCPLM', 'Missouri Metro', 'KCPLK', 'Kansas Metro', 
'WSTRS', 'Kansas Central South', 'WSTRC', 'Kansas Central'),

ALFD.SUBSTATION_ID,
ALFD.FEEDER_ID,
ALFD.TRANSFORMER_ID,

D1_DVC.DEVICE_TYPE_CD,
DECODE(TRIM(CI_SP_CHAR.CHAR_VAL), '1', '120', '2', '120/120', '3', '120/208', '4', '120/240', 
'5', '120/240/208', '6', '240/240', '7', '240/480', '8', '277/480', '9', '480/480')
